name: "Test swazzler-tests"

on:
  workflow_dispatch:

env:
  ANDROID_BUILD_TOOLS_HOME: "/usr/local/lib/android/sdk/build-tools/32.0.0"

jobs:
  call-swazzler-tests-subset:
    uses: ./.github/workflows/swazzler-tests-subset.yml


