name: "Run subset of swazzler-tests"

on:
  pull_request:
  workflow_dispatch:

env:
  ANDROID_BUILD_TOOLS_HOME: "/usr/local/lib/android/sdk/build-tools/32.0.0"

jobs:
  runSwazzlerTests:
    name: "Run Gradle Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sdk
        uses: actions/checkout@v4

      - name: Install Java machine
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      # make sure version in gradle.properties matches the version of embrace-swazzler3 version
      - name: "Publish Sdk locally"
        run: ./gradlew publishToMavenLocal --no-daemon

      - name: Checkout Swazzler-Test
        uses: actions/checkout@v4
        with:
          repository: embrace-io/swazzler-test
          ref: master
          path: ./swazzler-test
          token: ${{ secrets.CD_GITHUB_TOKEN || secrets.token }}

      - name: Configure git for submodules
        env:
          GITHUB_API_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
        run: git config --global url."https://${GITHUB_API_TOKEN}@github.com".insteadOf "https://github.com"

      # update all submodules
      - name: Git submodules remote update
        run: cd swazzler-test && git submodule update --remote --recursive --init --force

      - name: "Publish Swazzler locally"
        run: cd swazzler-test/embrace-swazzler3 && ./gradlew publishToMavenLocal --no-daemon

      - name: "Run Gradle Tests"
        run: |
          echo "Running Gradle tests"        
          cd swazzler-test && ./gradlew :functional-tests:swazzlerTests --tests "io.embrace.android.gradle.swazzler.tests.MinimumSurvivalTests" --stacktrace

      - name: "Test Results"
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: swazzler-test-results
          path: swazzler-test/functional-tests/build/reports/tests/swazzlerTests/